services:
  - type: web
    name: nexify
    env: docker
    repo: https://github.com/marklouie-abayhon/nexify-search-engine
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: 'composer install && npm install && npm run build'
    startCommand: 'php artisan serve --host=0.0.0.0 --port=10000'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
