services:
  - type: web
    name: nexify-search-engine
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
