services:
  - type: web
    name: nexify-search-engine
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://nexify-search-engine.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: metro.proxy.rlwy.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ozuSEZpPowKQCSPCEHFWtegOQLspHfuk
